### ISSUE TITLE
使用 navigationFragment.pushFragment 底部 TabBarFragment 消失（被新fragment 盖住）

### ISSUE THREAD

**Issue by currer** [listenzz/AndroidNavigation#11]
好像，使用TabBarFragment后，tab单页中的 navigationFragment 跳转（使用pushFragment ）方法，底部导航栏会消失，使用 replace 是不消失的。这是BUG吗？如果不是，跳转后的fragment如何弹出底部TabBarFragment呢？
不过可以通过requireFragmentManager().add(...)的方式正常添加，不会遮挡TabBarFragment

**Comment by listenzz** [comment]
这是默认行为

如果不希望这样，在 navigationFragment 的 rootFragment 重写以下方法，返回 false

```java
@Override
protected boolean hidesBottomBarWhenPushed() {
        return false;
 }
```
正如 demo 中 TestStatusBarFragment 这个类所做的那样

**Comment by currer** [comment]
感谢
