### ISSUE TITLE
调用appendStatusBarPadding显示异常

### ISSUE THREAD

**Issue by oujieying** [listenzz/AndroidNavigation#16]
sdk为19的机型，自定义ToolBar的情况调用appendStatusBarPadding，ToolBar上面显示了多余的空白

**Comment by listenzz** [comment]
你好，能提供截图不

**Comment by listenzz** [comment]
是否开启了沉浸式, 如果没开启，是不需要添加 padding 的

**Comment by listenzz** [comment]
此 issue 太久没有活跃，因此关闭
