### ISSUE TITLE
使用NavigationFragment()时怎么关闭页面跳转时的动画

### ISSUE THREAD

**Issue by LaoXiZi** [listenzz/AndroidNavigation#19]
使用NavigationFragment()时怎么关闭页面跳转时的动画?
BlankFragment blankFragment = new BlankFragment();
 NavigationFragment navigationFragment = getNavigationFragment();
 navigationFragment.关闭动画;
 navigationFragment.pushFragment(blankFragment);

**Comment by listenzz** [comment]
出于什么原因考虑需要关闭动画呢？使用 replace 代替 push 可否？

**Comment by LaoXiZi** [comment]
有几个页面关联度大,没有动画看着合理一些.
replace代替Toolbar还要自己写.

**Comment by listenzz** [comment]
navigationFragment.replaceFragment(blankFragment) 也会自动创建 toolbar 的，如果不需要返回之前的页面，使用 replace 比较合适。有考虑重载 push，增加一个参数来控制动画，不过可能两三周后才有时间实现此功能。

**Comment by listenzz** [comment]
现在支持跳转时自定义动画了，以下代码可以在 push 时关闭动画

```
navigationFragment.pushFragment(blankFragment, Anim.Delay);
```

**Comment by 3-BodyCoding** [comment]
pushFragment动画API怎么没了@listenzz

**Comment by listenzz** [comment]
@AndroidJohnsonWang 出了点小问题，新版本移除了。

**Comment by 3-BodyCoding** [comment]
@listenzz 希望尽快能加上去，谢谢

**Comment by listenzz** [comment]
@AndroidJohnsonWang 请问你是要禁止动画吗？

**Comment by 3-BodyCoding** [comment]
@listenzz 是要自定义进入和退出动画，目前发现setAnimation有点问题，退出动画无法生效

**Comment by listenzz** [comment]
@AndroidJohnsonWang  如果对默认的动画不满意，想全局自定义，只要把本库 anim 文件夹下那几个动画文件拷贝到你的工程的 anim 文件下，作相应改动即可，gradle 在打包时会替换掉同名的资源文件

**Comment by 3-BodyCoding** [comment]
@listenzz 全局可以这样，但是现在是对某个界面才改变动画
