### ISSUE TITLE
马上要开一个新的项目,准备用这个UI框架,不知道会不会遇到什么问题,笔者推荐我在新开的项目中使用吗?

### ISSUE THREAD

**Issue by LaoXiZi** [listenzz/AndroidNavigation#20]
马上要开一个新的项目,准备用这个UI框架,不知道会不会遇到什么问题,笔者推荐我在新开的项目中使用吗?

**Comment by LaoXiZi** [comment]
马上要开一个新的项目,准备用这个UI框架,不知道会不会遇到什么问题,笔者推荐我在新开的项目中使用吗?

**Comment by listenzz** [comment]
目前我司也在使用，放心使用吧，有我在呢。

**Comment by LaoXiZi** [comment]
嗯,那我就用了,想想项目里都是Fragment都有点小激动..
