### ISSUE TITLE
setStatusBarTranslucent无效

### ISSUE THREAD

**Issue by Oo121oO** [listenzz/AndroidNavigation#22]
vivo x6plus d这个机器上，无论在AwsomActvity还是AwsomFragment设置setStatusBarTranslucent(false)，都无法关闭沉浸式。很无语啊。

**Comment by listenzz** [comment]
沉浸式默认就是关闭的，是不是只有这台机器会这样？

**Comment by Oo121oO** [comment]
是的。只有这台机器是这样的。无论怎么设置都没有用。Theme设false，代码设false，没有其他任何设置，都不行。还是默认沉浸式。

**Comment by listenzz** [comment]
建议看看其它 APP 是否也是这样
