### ISSUE TITLE
presentFragment后，toolbar空指针

### ISSUE THREAD

**Issue by 3-BodyCoding** [listenzz/AndroidNavigation#24]
使用pushFragment正常，使用presentFragment后，到新界面toolbar空指针

**Comment by listenzz** [comment]
```java
NavigationFragment nav = new NavigationFragment();
TargetFragment target = new TargetFragment();
nav.setRootFragment(target);
this.presentFragment(nav);
```

需要将目标包裹在 NavigationFragment 里面，因为只有在 NavigationFragment 里面，才会创建 toolbar

**Comment by 3-BodyCoding** [comment]
这是我的代码：
   AddContactsFragment addContactsFragment = new AddContactsFragment();
  NavigationFragment navigationFragment = new NavigationFragment();
  navigationFragment.setRootFragment(addContactsFragment);
  thisNavigationFragment.presentFragment(addContactsFragment,REQUEST_CODE);

**Comment by listenzz** [comment]
那就奇怪了，你用的是哪个版本？
可否粘贴下错误堆栈

**Comment by 3-BodyCoding** [comment]
thisNavigationFragment.presentFragment(addContactsFragment,REQUEST_CODE);
这个要改成
thisNavigationFragment.presentFragment(navigationFragment,REQUEST_CODE);
不会报错了，不过又出现了新问题，左边设置的返回按键没了

**Comment by listenzz** [comment]
NavigationFragment 的 rootFragment 默认就是没有返回按钮的，如果你有需要，可以通过 setLeftBarButtonItem 设置。

**Comment by listenzz** [comment]
请参考 demo 是如何设置一个 '关闭' 按钮的

**Comment by 3-BodyCoding** [comment]
嗯，这个知道。意思是需要返回值的跳转必需要设置setRootFragment？因为不设置这个，会报toolbar空指针.
![image](https://user-images.githubusercontent.com/15881869/41107017-ee948ac2-6aa3-11e8-9c25-3696ef6585cc.png)

**Comment by listenzz** [comment]
并不是一定要套个 NavigationFragment, 如果你的 addContactsFragment 没有使用 toolbar 相关 api 的话

`popFragment` 也是可以返回值的, 不过此时 `onFragmentResult` 的  requestCode 为 0， 需要通过 resultCode 来区分返回类型

**Comment by 3-BodyCoding** [comment]
嗯，发现了一个简单办法，设置setNavigationIcon可以为这种情况添加返回按钮，然后监听setNavigationOnClickListener，dismissFragment即可
presentFragment的动画是写死的？@listenzz

**Comment by listenzz** [comment]
@AndroidJohnsonWang 是的
