### ISSUE TITLE
你的类库和demo跑不起来

### ISSUE THREAD

**Issue by AndMy** [listenzz/AndroidNavigation#26]
好多错啊
![default](https://user-images.githubusercontent.com/7222340/41846998-22e9c188-78ab-11e8-9e68-8d87ab79b505.png)
![default](https://user-images.githubusercontent.com/7222340/41847006-2c29ee94-78ab-11e8-8661-5e79c657c763.png)
![default](https://user-images.githubusercontent.com/7222340/41847023-3aa2f722-78ab-11e8-826b-6d01c68c02ec.png)

**Comment by listenzz** [comment]
请问你是用 Eclipse 打开的么

**Comment by AndMy** [comment]
是Android  studio

**Comment by listenzz** [comment]
翻个墙试试，可能有些包没能拉下来，你没有改过 build.gradle 里面的配置吧

**Comment by AndMy** [comment]
navigation类库的build.gradle 里面的获取版本号的，我把最上面的注释掉了，然后所有的build里的compileSdkVersion从27降到25，其他的没变

**Comment by listenzz** [comment]
支持库必须是 27.1.0 以上的，恢复原样再试试？

**Comment by AndMy** [comment]
我是这样写的
compileSdkVersion 25
 buildToolsVersion 27.3.1

**Comment by listenzz** [comment]
因为你是直接下载到本地，而不是通过 git clone 的方式，所以你需要做些额外的修改：

把 navigation/build.gradle 中的 `gitVersionCode()`  替换成任意数字，比如 1

![jietu20180625-194959](https://user-images.githubusercontent.com/4386370/41848941-d406a96c-78b1-11e8-90c8-86d055840ce9.jpg)

打开侧边的 gradle 选项卡，点击同步按钮

![jietu20180625-195030](https://user-images.githubusercontent.com/4386370/41849013-1b7dc10e-78b2-11e8-9753-e9c534256845.jpg)

同步完成后，会问你要不要重试，点击重试选项

![jietu20180625-195051](https://user-images.githubusercontent.com/4386370/41849047-3369c1dc-78b2-11e8-9a52-d10c8d286c7d.jpg)

在弹出来的对话框中选择 Don't remind me again for this project

![jietu20180625-195127](https://user-images.githubusercontent.com/4386370/41849128-6cfee170-78b2-11e8-96bd-13fc654b575d.jpg)

然后应该处于可运行状态了

![jietu20180625-195152](https://user-images.githubusercontent.com/4386370/41849148-7e2ef930-78b2-11e8-8c6d-27d1662923b9.jpg)

**Comment by AndMy** [comment]
感谢您的细心解答，已经完美运行，十分感谢

**Comment by AndMy** [comment]
还有这个库的底部导航，消息提示功能现在只能设置字符串，能不能设置小红点啊，找了半天没找到。。。

**Comment by listenzz** [comment]
你好，还不可以设置小红点，这周末增加此功能

**Comment by AndMy** [comment]
好的，感谢，近期要开新项目了，准备用大佬的库，谢谢大佬
能留个联系方式么，或者有群号么

**Comment by listenzz** [comment]
不用客气，有问题及时反馈。联系方式发你邮箱。

**Comment by listenzz** [comment]
@AndMy 现已支持红点。

以后不同的问题分不同的 issue 来提哦
