### ISSUE TITLE
setAwesomeTitle 不起作用

### ISSUE THREAD

**Issue by yocloud** [listenzz/AndroidNavigation#27]

**Comment by listenzz** [comment]
设置页面标题，通常是在 fragment 的 `onActivityCreated` 中调用 `setTitle` 来设置。
能贴下代码来演示你是如何调用 setAwesomeTitle 的吗？

**Comment by yocloud** [comment]
![snip20180626_2](https://user-images.githubusercontent.com/22676419/41885676-9c3dfb64-792b-11e8-916c-26f55165c7d5.png)
![snip20180626_3](https://user-images.githubusercontent.com/22676419/41885734-d7aa0602-792b-11e8-9843-d1234b60856e.png)
在onCreateView 调用setAwesomeTitle的

**Comment by listenzz** [comment]
mToolbar 是怎么来的呢？如果 fragment 嵌套在 `NavigationFragment` 中，会在 `onViewCreated` 这个生命周期函数为你自动创建 Toolbar ,然后才可以通过 AwesomeFragment#setTitle 设置标题

**Comment by yocloud** [comment]
mToolbar 是在xml布局定义的 ,因为之前是有这么个错误
![snip20180626_4](https://user-images.githubusercontent.com/22676419/41886484-2155367a-792f-11e8-927d-f94cd837ccf2.png)

**Comment by yocloud** [comment]
这个问题已解决,十分感谢!

**Comment by listenzz** [comment]
好的，明白了。
参考下面的做法：

```java
public class CoordinatorFragment extends AwesomeFragment {

    AwesomeToolbar toolbar;

    protected AwesomeToolbar onCreateAwesomeToolbar(View parent) {
        return toolbar;
    }

    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_coordinator, container, false);

        toolbar = root.findViewById(R.id.toolbar);

        return root;
    }

}
```

**Comment by listenzz** [comment]
然后在 onActivityCreated 中调用 setTitle 设置标题
