### ISSUE TITLE
如何改变底部Tab 的位置?

### ISSUE THREAD

**Issue by liuxuesong001** [listenzz/AndroidNavigation#28]
我的需求想把下面 2个Tab 放在上边

**Comment by liuxuesong001** [comment]
NavigationFragment 导航位置 首页取消toolbar 然后放在上面 这个可以实现吗?

**Comment by listenzz** [comment]
可以通过自定义容器的方式解决,  [参考这个类](https://github.com/listenzz/AndroidNavigation/blob/master/demo/src/main/java/com/navigation/toolbar/ViewPagerFragment.java)
