### ISSUE TITLE
ToolbarButtonItem的setEnabled问题

### ISSUE THREAD

**Issue by ebenmo** [listenzz/AndroidNavigation#29]
ToolbarButtonItem在初始化的时候如果Enabled为false按钮会变灰，但如果后面调用setEnabled为true时漏了更改按钮的颜色，应该要在
public void setEnabled(boolean enabled) {
        if (button != null) {
            button.setEnabled(enabled);
        }
    }

里加上改颜色的代码

**Comment by listenzz** [comment]
更新到 1.8.8 即可
