### ISSUE TITLE
请问用作dialog显示的 fragment 能在没有此框架的Activity下以dialog的形式显示不？

### ISSUE THREAD

**Issue by bananaCaptain** [listenzz/AndroidNavigation#31]
作者你好！如题
请问用作dialog显示的 fragment 能在没有此框架的Activity下以dialog的形式显示不？
就是用作dialog显示的fragment可否在任意的项目中重用？ 
感谢

**Comment by bananaCaptain** [comment]
Activity 能直接使用 被定义为DialogFragment的类不？

**Comment by listenzz** [comment]
不能哦

**Comment by listenzz** [comment]
也不是绝对不能，只要你的 Activity 实现 PresentableActivity 这个接口即可

**Comment by bananaCaptain** [comment]
好的！我试一下，麻烦了。只是希望写了的dialog可以通用，重复使用。麻烦了
