### ISSUE TITLE
底部TabBar能支持左右两侧模式不？

### ISSUE THREAD

**Issue by bananaCaptain** [listenzz/AndroidNavigation#32]
作者你好！如题目！现在有这样的需求，是用再平板上的。
TabBar能支持设置到做侧不？或者有没有好的方案解决提示一下。
还有此库会对平板的场景进行加强不？
未来可能会出现更多的手机与平板二合一的折叠手机，到时候支持平板多变的导航功能，多Fragment控制的需求会变得更多。
感谢作者

**Comment by listenzz** [comment]
TabBar 是可以自定义的，实现 TabBarProvider ，并在 TabBarFragment 添加到 UI 层级之前通过 TabBarFragment#setTabBarProvider 配置即可。

**Comment by bananaCaptain** [comment]
@listenzz 作者你好看了TabBarFragment源码发现虽然可以用外部TabBar,但是还是强制了Gravity.BOTTOM.只能在底部.我想设置到左侧,那就只能重写TabBarFragment了?

**Comment by listenzz** [comment]
@bananaCaptain 是的，自定义一个恰当的容器是较好的实践。
