### ISSUE TITLE
一个activity页面同时显示两个fragment的情况支持不?

### ISSUE THREAD

**Issue by bananaCaptain** [listenzz/AndroidNavigation#33]
作者你好!
请问这个框架现在有支持一个activity页面同时显示两个或多个fragment或者局部使用fragment的方案不?
应该怎样处理?
真的麻烦了.

**Comment by listenzz** [comment]
一个 Activity 只能有一个根 Fragment，但 Fragment 可以同时显示多个子 Fragment，具体参看 DrawerFragment 的实现

**Comment by bananaCaptain** [comment]
好的麻烦了
