### ISSUE TITLE
哪个方法可以立即触发onCustomStyle？

### ISSUE THREAD

**Issue by AndyLeeBlue** [listenzz/AndroidNavigation#38]
1：问题缘由：夜间模式和白天模式的切换，需要更换全局的status bar，tool bar，tab bar的背景色和样式，并且立即生效，虽然有fragment对应的3个setNeedsAppearanceUpdate方法，但是使用起来还是不如修改style的方便。

2：另外fragment的preferredToolbarColor方法中，getAwesomeToolbar得到的toolbar，setTitleTextColor可以产生效果，但是setButtonTintColor却无效，这个是bug吗？

3：fragment的preferredNavigationBarColor方法无效？请问正确的使用方式。

谢谢！

**Comment by listenzz** [comment]
1. 暂时没有办法触发 onCustomStyle，即使触发也没有办法对现有界面发生影响，它影响的是未来的界面。

2. 不要直接修改 toolbar 的属性，通过 style 设置 style.setToolbarTintColor，然后调用 setNeedsToolbarAppearanceUpdate 即可。

3. preferredNavigationBarColor 仅对 Android 8.0 以上版本生效，用于修改底部导航栏的颜色。
