### ISSUE TITLE
导航栏按钮切换界面闪烁

### ISSUE THREAD

**Issue by AndyLeeBlue** [listenzz/AndroidNavigation#39]
换了最新版本，之前没这个问题。导航栏第一次加载界面时候，会闪烁一次，再次进来就不会了。导航栏就是页面最下面的那个Tabbar。

**Comment by listenzz** [comment]
demo 不会哦，方便录个屏或提供 gif ?

**Comment by AndyLeeBlue** [comment]
特地试了下demo也会，demo是白色背景因此不明显，我的是深色主题，因此特别明显。手机是华为10，9.0版本

**Comment by listenzz** [comment]
你是从哪个版本升级到哪个版本呢？ 方便的话用二分法找出导致不正常的那个版本？

**Comment by listenzz** [comment]
麻烦提供下主题颜色

**Comment by AndyLeeBlue** [comment]
从2.1.9到昨天的2.3.4，都2.3.5啦，你真快

**Comment by AndyLeeBlue** [comment]
> 麻烦提供下主题颜色

<color name="night_main_back_bg">#0e1835</color>

**Comment by listenzz** [comment]
就是首次切换的时候有问题，闪烁一下？

**Comment by AndyLeeBlue** [comment]
> 就是首次切换的时候有问题，闪烁一下？

是的，是的

**Comment by listenzz** [comment]
试下 2.2.4 和 2.3.0，我怀疑是 2.3.0 导致的

**Comment by AndyLeeBlue** [comment]
好的，期待版本更新，谢谢~

**Comment by listenzz** [comment]
有结果没？确定是 2.3.0 的问题？

**Comment by AndyLeeBlue** [comment]
224不闪，230闪烁

**Comment by listenzz** [comment]
2.4.0 已经发布，看下有没有问题

**Comment by AndyLeeBlue** [comment]
2.4.0不闪烁了

**Comment by listenzz** [comment]
好的，感谢反馈。
