### ISSUE TITLE
能否提供一个方法可以快速的得到上一级的fragment？

### ISSUE THREAD

**Issue by AndyLeeBlue** [listenzz/AndroidNavigation#41]
实际使用中，很多情况是A--push->B，B经常要和A交互，有没有一个快速方法？

**Comment by listenzz** [comment]
在 A  调用 FragmentHelper.getLatterFragment(requireFragment(), this) 可得到 B

在 B 调用 FragmentHelper.getAheadFragment(requireFragment(), this) 可得到 A
