### ISSUE TITLE
fitSystemWindows无法起作用问题

### ISSUE THREAD

**Issue by RealFeeling** [listenzz/AndroidNavigation#46]
作者您好，在使用该库过程中，发现Activity在布局中的根布局设置fitSystemWindows无法起作用，页面的内容顶部一小部分会被藏到statusbar下面， 必须要在布局中使用paddinng top或者margin top 才行，但是目前市面上手机的statusbar的高度不统一，无法有一个确定的值去设置，望作者能修复一下该问题，谢谢

**Comment by listenzz** [comment]
本库重写了 `OnApplyWindowInsetsListener`，所以 `fitSystemWindows` 不再生效：

https://github.com/listenzz/AndroidNavigation/blob/master/navigation/src/main/java/com/navigation/androidx/AppUtils.java#L144

本库会自动创建 Toolbar，并适配状态栏高度，如果需要自己创建 Toolbar，请参考 

https://github.com/listenzz/AndroidNavigation/blob/master/demo/src/main/java/com/navigation/statusbar/CustomStatusBarFragment.java#L44

如果不需要 Toolbar, 请参考

https://github.com/listenzz/AndroidNavigation/blob/master/demo/src/main/java/com/navigation/toolbar/NoToolbarFragment.java#L25

其它情况，可以通过调用 `appendStatusBarPadding` 来适配。

**Comment by RealFeeling** [comment]
感谢作者，我的问题已解决
