### ISSUE TITLE
无法presentFragment问题

### ISSUE THREAD

**Issue by RealFeeling** [listenzz/AndroidNavigation#47]
今天在fragment中使用presentFragment方法时，发现没起作用，单点调试后发现，在使用该方法前在Activity上创建了一个DialogFragment来显示加载中，所以导致canPresentFragment方法中获取DialogFragment不为空，所以无法进一步跳转新的fragment。

问题是，在调用presentFragment方法前，已经将这个dialogfragment给dismiss掉了，依然不凑效，望作者给个解决思路，谢谢

**Comment by listenzz** [comment]
在调用 dialog.dismiss() 后，调用 FragmentHelper.executePendingTransactionsSafe(dialog.requireFragmentManager());

**Comment by listenzz** [comment]
或者升级到 7.0.0，不再受普通 DialogFragment 的影响

**Comment by RealFeeling** [comment]
> 或者升级到 7.0.0，不再受普通 DialogFragment 的影响

作者您好，我这边尝试将版本升级到最新的7.1.0，然后就出现了未知错误无法通过编译：

Manifest merger failed with multiple errors, see logs

再点击运行就有个小提示： Default activity not found

有点莫名其妙

运用gradlew processDebugManifest --stacktrace 命令进行查找问题也没有找到问题。

尝试切换到7.0.0同样的问题再次出现，目前是设置为6.0.0才能正常运行，6.9.0不知为何无法下载。

望作者解答，谢谢

**Comment by listenzz** [comment]
可能是墙的问题 https://bintray.com/listenzz/maven/androidx/7.1.0

**Comment by RealFeeling** [comment]
下载是没问题，就是要运行项目时会出现以下问题：
![QQ图片20200826220245](https://user-images.githubusercontent.com/12228071/91314082-c0206980-e7e8-11ea-975a-0c0f1c91e5fd.png)

切换到6.0.4后，则可以正常运行项目，似乎7.0.0的某些改动影响了项目运行，我继续研究一下
![2](https://user-images.githubusercontent.com/12228071/91314195-e1815580-e7e8-11ea-8b84-ef581399d33e.png)
