### ISSUE TITLE
dismissFragment的小问题

### ISSUE THREAD

**Issue by RealFeeling** [listenzz/AndroidNavigation#48]
1. 在继承了AwesomeActivity的Activity里（没有设置任何rootFragment），直接通过点击按钮present出来的Fragment无法dismissFragment。目前未知具体原因

2. 建议能在presentFragment时，能自定义打开的动画。同样的dismiss时也能指定动画，望作者回复，谢谢

**Comment by RealFeeling** [comment]
3.activity和fragment都有重写onBackPressed方法的时候，fragment的该方法无法拦截，只能走activity的这个方法~

**Comment by listenzz** [comment]
1. 已验证，确实是不行。可如果没有设置 rootFragment,  present 是没有意义的
2. 暂时不提供为每个页面自定义动画的功能，因为没时间。不过可以全局覆盖，在你自己的工程的 res/anim 目录下，使用和本库同名的动画文件（xml）即可
3. 不要拦截 Activity 的 onBackPressed ，重写 handleBackPressed 即可
