### ISSUE TITLE
ViewAppear相关逻辑如何升级？

### ISSUE THREAD

**Issue by bananaCaptain** [listenzz/AndroidNavigation#49]
作者你好我们的项目使用了     implementation 'com.navigation.androidx:androidx:4.3.1'，现在无法依赖 之后的新版本。发现ViewAppear相关的逻辑全部没有了。请问有替换方案不。因为关联的androidx库也无法升级了。感谢

**Comment by listenzz** [comment]
使用 ViewPager2 代替 ViewPager，在 onResume 处理懒加载问题
