### ISSUE TITLE
getParentFragment为空问题

### ISSUE THREAD

**Issue by RealFeeling** [listenzz/AndroidNavigation#50]
作者您好，使用中出现的问题如下：

MainActivity 的 rootFragment 为TabBarFragment：

tabBarFragment = new TabBarFragment();
tabBarFragment.setChildFragments(fragment1, fragment2, fragment3, fragment5, fragment4);
tabBarFragment.setTabBarProvider(new MainTabProvider());

setActivityRootFragment(tabBarFragment);

在其中一页Tab的Fragment通过点击按钮presentFragment出来的新Fragment里，调用getParentFragment为空。

发现这个问题是因为发现dissmiss Fragment返回后onFragmentResult没执行，跟踪调试后发现以上问题。

**Comment by RealFeeling** [comment]
presentFragment时在presentFragment方法中，getParentAwesomeFragment()获取到的是 tabBarFragment：

AwesomeFragment parent = getParentAwesomeFragment();
            if (parent != null) {
                if (definesPresentationContext()) {
                    presentFragmentInternal(AwesomeFragment.this, fragment, requestCode, completion);
                } else {
                    parent.presentFragment(fragment, requestCode, completion);
                }
                return;
            }

然后definesPresentationContext()为false， （不太清楚这个字段的意思，望作者能解释一下。）
所以又重新执行了当前方法，再getParentAwesomeFragment()时就为 Null了。

我也尝试过在presentFragment前把definesPresentationContext 设置为true，这样就能解决上述getParentFragment为空问题，但是tabbar的页面会显示错乱。

**Comment by listenzz** [comment]
present 出来的 fragment，它的 parentFragment 是为空的，因为这个 fragment 和底下的 TabBarFragment 是兄弟，它们都属于 Activity 的fragment。

在 TabBarFragment 或其子 fragment 调用 getPresentedFragment 可以获取你 present 出来的那个 fragment。在你 present 出来的那个 fragment 中调用 getPresentingFragment 可以获得 TabBarFragment。

在 TabBarFragment 的任意层次子 fragment 中调用 getTabBarFragment 可以获得 TabBarFragment。

这套 api 是仿 ios 的，问一下你身边的 ios 同是，就会明白。

definesPresentationContext 是高级用法，也是仿 iOS 的，一般情况下用不到，只有做滴滴出行那样的UI层级结构，不同页面共享同一份地图，才会用到。

**Comment by listenzz** [comment]
TabBarFragment 的某个孙 fragment 调用 presentFragment，结果是返回给那个孙 fragment 的

**Comment by RealFeeling** [comment]
大概明白，还有个小疑问，既然present出来的Fragment属于activity，那我尝试了下，在这个fragment里又点击按钮present出第二个fragment，照理说这个第二个fragment是子fragment，但是getParentAwesomeFragment()依然返回空，而且第二个fragment在dismiss后，第一个fragment的onFragmentResult没执行。

**Comment by listenzz** [comment]
@RealFeeling  present 出来的 fragment 总是属于 Activity 的，除非使用了 definesPresentationContext。onFragmentResult 不执行稍后我验证下。

**Comment by listenzz** [comment]
@RealFeeling 亲测，有结果返回。

**Comment by RealFeeling** [comment]
我这边从第二个Fragment直接getPresentingFragment()是可以获取到第一个Fragment的，就是直接dismiss第一个fragment没有获取到返回，具体问题我再研究一下，感谢

**Comment by RealFeeling** [comment]
作者您好，我这边早上查出来了没接收到返回结果的问题。

如你说的，present出来的fragment的parentFragment都为空，

所以在第二个fragment调用dismiss后，由于parentfragment为空，所以会执行以下代码

if (presentableActivity != null) {
                presentableActivity.dismissFragment(this, completion);
            }

即走到AwesomeActivity去dissmiss。代码如下

protected void dismissFragmentInternal(AwesomeFragment fragment, @Nullable Runnable completion) {
        AwesomeFragment presented = getPresentedFragment(fragment);
        if (presented != null) {
            FragmentHelper.handleDismissFragment(fragment, presented, null);
            if (completion != null) {
                completion.run();
            }
            return;
        }else{
            FragmentHelper.handleDismissFragment(fragment);
        }

        AwesomeFragment presenting = getPresentingFragment(fragment);
        if (presenting != null) {
            FragmentHelper.handleDismissFragment(presenting, fragment, fragment);
        }

        if (completion != null) {
            completion.run();
        }
    }

我这边跟踪代码到AwesomeFragment presenting = getPresentingFragment(fragment);这一行，发现
presenting 获取到为空。所以导致第一个fragment没有执行onFragmentResult。

![image](https://user-images.githubusercontent.com/12228071/96815755-c2e9b480-144f-11eb-9c6c-828eb9bd8e00.png)

目前还未知为何在Activiy里执行getPresentingFragment(fragment)结果为空，但是直接在第二个fragment里调用getPresentingFragment()是可以获取到第一个fragment的。

我这边再研究一下，作者如果有思路望回复。

**Comment by listenzz** [comment]
你是怎么 dismiss 的？是调用了被 present 出来的那个 fragment 或其子 fragment 的 dismissFragment 方法吗？

**Comment by RealFeeling** [comment]
在第二个Fragment中，我把这两行代码放在一起执行：

getPresentingFragment()；
dismissFragment();

通过运行发现第一行能获取到PresentingFragment， 第二行PresentingFragment为空。
继续跟踪发现两行代码都会执行FragmentHelper里的getFragmentBefore方法。

getPresentingFragment()；时该方法能顺利执行完。

dismissFragment();时在第一句!fragment.isAdded()就返回了true，导致返回了null
![image](https://user-images.githubusercontent.com/12228071/96817406-d9910b00-1451-11eb-8f63-9540fdce48fe.png)

**Comment by RealFeeling** [comment]
层次结构就是tabbar中的一页present出来第一个fragment，再从第一个fragment里present出来第二个fragment。

**Comment by listenzz** [comment]
或者提供个小 demo 给我

**Comment by RealFeeling** [comment]
![image](https://user-images.githubusercontent.com/12228071/96817763-997e5800-1452-11eb-9b8e-56d5f8f8c5f0.png)

发现是被注释掉的这行代码导致的问题，因为提前dismiss了，所以在获取presentingFragment时，fragment.isAdded()已经为false，所以导致获取为空，这里我注释掉这行代码后就能正常获取到返回结果了。

![image](https://user-images.githubusercontent.com/12228071/96817929-f974fe80-1452-11eb-8fd6-5fbd337fd601.png)

这里考虑把上下两块代码替换一下顺序位置，不知是否会导致其他问题。

**Comment by listenzz** [comment]
你使用的版本是 7.3.0 吗？

**Comment by RealFeeling** [comment]
应该是7.2.0，这边没有使用依赖，直接作为lib导入了，请问在哪可以看到每个版本修改的内容呢？谢谢

**Comment by listenzz** [comment]
这些改动没有 changelog。

你更新下代码

**Comment by listenzz** [comment]
查看 git 记录，没发现你上面列举的写法，最新的是这个样子的

```java
    protected void dismissFragmentInternal(AwesomeFragment fragment, @Nullable Runnable completion) {
        AwesomeFragment presented = getPresentedFragment(fragment);
        if (presented != null) {
            FragmentHelper.handleDismissFragment(fragment, presented, null);
            if (completion != null) {
                completion.run();
            }
            return;
        }

        AwesomeFragment presenting = getPresentingFragment(fragment);
        if (presenting != null) {
            FragmentHelper.handleDismissFragment(presenting, fragment, fragment);
        }

        if (completion != null) {
            completion.run();
        }
    }
```

**Comment by RealFeeling** [comment]
感谢，更新了这段代码问题解决了
