### ISSUE TITLE
大佬，问个跳转动画问题

### ISSUE THREAD

**Issue by keternity** [listenzz/AndroidNavigation#53]
使用pushFragment方法，我想用TransitionAnimation.Present的动画，怎么设置啊

**Comment by listenzz** [comment]
动画可以全局替换，在你自己项目的 res/anim 文件夹下，放置和默认动画相同的文件名的动画文件，即可覆盖默认的动画文件。

**Comment by keternity** [comment]
我这边的需求是，大部分页面是用TransitionAnimation.Push（侧滑切换动画），有些特殊的场景页面跳转得用TransitionAnimation.Present（从下往上的切换动画）

**Comment by listenzz** [comment]
那为何不直接使用 presentFragment ?

我暴露个方法，支持下。

**Comment by keternity** [comment]
如果用presentFragment ，后续新页面再跳转的话，就不能用pushFragment方法了。我这项目逻辑比较奇葩，在流程里面会需要3种跳转方式，正常的push动画，然后到选择相册的时候会使用present动画，相册选择的时候不是直接返回，会跳到裁剪页面，这时候不需要跳转动画

**Comment by listenzz** [comment]
A present -> 相册 

相册 push ->  裁剪，不要动画

裁剪 返回  -> A 

如果是上面这种交互。A present 相册的时候，把相册包裹在 NavigationFragment 中，再由相册 push 到裁剪，裁剪 setResult ，然后裁剪调用 dismissFragment，A 是可以在 onFragmentResult 中接收到结果的

**Comment by keternity** [comment]
这个方式不错，谢谢大佬
