### ISSUE TITLE
大佬，请教一个问题

### ISSUE THREAD

**Issue by keternity** [listenzz/AndroidNavigation#55]
首先感谢大佬的框架。
我这边产品有个需求，准备push的页面有个RecyclerView，RecyclerView里面item比较复杂，产品要求想push完成的时候，页面也加载完成，就像微信跳转到聊天页面的时候一样，页面加载和动画是同步的。我这边实现之后发现（在onViewCreated里面给adapter塞入数据），push动画会吃掉，然后直接跳转到页面了。
求大佬指教一下，有没有什么思路，膜拜

**Comment by keternity** [comment]
解决了，还是要感谢大佬强大的框架

**Comment by listenzz** [comment]
请问你是如何实现的？

**Comment by keternity** [comment]
用postponeEnterTransition，和startPost就可以了[狗头]
